# Generated by Django 5.1.4 on 2025-01-02 17:39

import blogpost.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_alter_blogpost_topic'),
        ('blogtopic', '0006_remove_blogtopic_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='topic',
            field=models.ForeignKey(default=blogpost.models.get_default_topic, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts_topic', to='blogtopic.blogtopic'),
        ),
    ]
