# Generated by Django 5.1.4 on 2025-01-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_alter_blogpost_topic'),
        ('blogtopic', '0004_alter_blogtopic_posts'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_blog_posts', to='blogpost.blogpost'),
        ),
        migrations.AlterField(
            model_name='user',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_blog_topics', to='blogtopic.blogtopic'),
        ),
    ]
