# Generated by Django 5.1.4 on 2025-01-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_posts_alter_user_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='topics',
        ),
    ]
