services:
  blogpostapp:
    container_name: blogpost_backend
    build: .
    volumes:
      - .:/app  
      - media:/app/media  # Volume for uploaded media files
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=blogpost
      - PG_HOST=database
      - PG_PORT=5432
    depends_on:
      database:
        condition: service_started
    command: >
      bash -c "
      sleep 10 &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000" 
  database:
    container_name: blogpost_db
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blogpost
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
  media: {}