# Generated by Django 5.1.4 on 2024-12-30 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogpost', '0002_initial'),
        ('blogtopic', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtopic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_topics_author', to='user.user'),
        ),
        migrations.AddField(
            model_name='blogtopic',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='blog_topics_posts', to='blogpost.blogpost'),
        ),
    ]
