# Generated by Django 5.1.4 on 2024-12-30 11:34

import blogtopic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogtopic', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtopic',
            name='author',
            field=models.ForeignKey(default=blogtopic.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='blog_topics_author', to='user.user'),
        ),
    ]
