# Generated by Django 5.1.4 on 2025-01-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_alter_blogpost_topic'),
        ('blogtopic', '0003_alter_blogtopic_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtopic',
            name='posts',
            field=models.ManyToManyField(null=True, related_name='blog_topics_posts', to='blogpost.blogpost'),
        ),
    ]
